#!/usr/bin/env python3
"""Mechanical checks for the two scorecards. Facts are checked; grades are not.

The scorecards mix two kinds of content. MEASURED FACTS — test count, coverage,
lint count, the weighted total — are verifiable and drift silently as the code
moves. JUDGMENTS — the per-dimension scores and the risk register — are opinions
that must be re-formed by a person or agent, never regenerated by a script.

This checks only the first kind, because the September 2026 lapse showed why:
a benchmark table and a README claim were wrong for weeks while every mechanical
gate stayed green, since every gate reads code and none reads prose. The
scorecards are prose. This gives them the one gate they can have.

Checks, in order of severity:

  ARITHMETIC (hard failure, exit 1). Each scorecard's weighted total must equal
      the weight-averaged scores in its own table, and the header must quote the
      same figure. A scorecard whose sums do not add up is worse than none.

  STALENESS (soft, exit 2). Implementation commits since the "Evaluated" date.
      Past a threshold the judgments are describing a codebase that no longer
      exists. This is what the session-start hook surfaces.

  FACTS (soft, exit 2; --measure only, because it runs the test suite). The
      test count, coverage and advisory-lint figures the health scorecard quotes,
      against what the repo measures now.

Exit 0 means the scorecards are arithmetically sound, current enough, and (with
--measure) quoting true numbers. It says nothing about whether the grades are
right — that is what /scorecard-refresh is for.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO = Path(__file__).resolve().parents[1]
HEALTH = REPO / "docs" / "PROJECT_HEALTH_SCORECARD.md"
SOTA = REPO / "docs" / "SOTA_COMPETITIVE_SCORECARD.md"

#: Implementation commits since the evaluation date before the judgments are
#: presumed stale. Three is deliberate: one commit is a fix, two is a feature,
#: three means the shape of the thing has moved.
STALE_AFTER_COMMITS = 3
#: Paths whose commits count as "implementation" for staleness. Docs-only
#: commits do not age a scorecard; they usually ARE the scorecard being updated.
IMPL_PATHS = ("src/", "scripts/", "tests/")

_ROW_RE = re.compile(r"^\| ([A-Za-z][^|]+?) \| (\d+)% \| \*\*([\d.]+)\*\* \|", re.M)
_TOTAL_RE = re.compile(r"\*\*Weighted total:\*\* ([\d.]+)/10")
_EVAL_RE = re.compile(r"^\*\*Evaluated:\*\* ([A-Z][a-z]+ \d{1,2}, \d{4})", re.M)


def _git(*args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=REPO, text=True).strip()


def check_arithmetic(path: Path, header_re: str) -> Dict[str, Any]:
    text = path.read_text()
    rows = _ROW_RE.findall(text)
    if not rows:
        return {"ok": False, "reason": "no scored rows found"}
    weight = sum(int(w) for _, w, _ in rows)
    computed = sum(int(w) * float(s) for _, w, s in rows) / weight
    stated_m = _TOTAL_RE.search(text)
    header_m = re.search(header_re, text)
    if not stated_m or not header_m:
        return {"ok": False, "reason": "weighted total or header figure not found"}
    stated, header = float(stated_m.group(1)), float(header_m.group(1))
    ok = abs(computed - stated) < 0.05 and stated == header
    return {
        "ok": ok, "rows": len(rows), "weights_sum_pct": weight,
        "computed": round(computed, 3), "stated": stated, "header": header,
        "reason": "" if ok else (
            f"table averages to {computed:.3f} but states {stated}"
            if abs(computed - stated) >= 0.05 else
            f"total {stated} disagrees with header {header}"
        ),
    }


def evaluated_on(path: Path) -> Optional[datetime]:
    m = _EVAL_RE.search(path.read_text())
    return datetime.strptime(m.group(1), "%B %d, %Y") if m else None


def commits_since(when: datetime) -> List[str]:
    out = _git("log", "--oneline", f"--since={when:%Y-%m-%d}", "--", *IMPL_PATHS)
    return [line for line in out.splitlines() if line.strip()]


def measure_facts() -> Dict[str, Any]:
    """Slow: runs the unit suite. Only on --measure."""
    out = subprocess.run(
        ["make", "verify"], cwd=REPO, capture_output=True, text=True,
    ).stdout + ""
    passed = re.search(r"=+ (\d+) passed", out)
    cov = re.search(r"Total coverage: ([\d.]+)%", out)
    lint = subprocess.run(
        ["flake8", "--max-line-length=120", "src/", "tests/"],
        cwd=REPO, capture_output=True, text=True,
    ).stdout
    return {
        "tests_passed": int(passed.group(1)) if passed else None,
        "coverage_pct": float(cov.group(1)) if cov else None,
        "flake8_findings": len([ln for ln in lint.splitlines() if ln.strip()]),
    }


def stated_facts(path: Path) -> Dict[str, Any]:
    t = path.read_text()
    tests = re.search(r"([\d,]+) passed", t)
    cov = re.search(r"([\d.]+)% coverage", t)
    lint = re.search(r"([\d,]+) advisory flake8 findings", t)
    return {
        "tests_passed": int(tests.group(1).replace(",", "")) if tests else None,
        "coverage_pct": float(cov.group(1)) if cov else None,
        "flake8_findings": int(lint.group(1).replace(",", "")) if lint else None,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--measure", action="store_true",
                    help="also run the suite and compare quoted facts (slow)")
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    ap.add_argument("--stale-after", type=int, default=STALE_AFTER_COMMITS)
    args = ap.parse_args()

    report: Dict[str, Any] = {"arithmetic": {}, "staleness": {}, "facts": None}
    hard_fail = soft_fail = False

    for name, path, hdr in (
        ("health", HEALTH, r"\*\*Overall health:\*\* \*\*([\d.]+)/10"),
        ("sota", SOTA, r"\*\*Overall competitive score:\*\* \*\*([\d.]+)/10"),
    ):
        if not path.exists():
            report["arithmetic"][name] = {"ok": False, "reason": "file missing"}
            hard_fail = True
            continue
        a = check_arithmetic(path, hdr)
        report["arithmetic"][name] = a
        hard_fail |= not a["ok"]

    dates = [d for d in (evaluated_on(HEALTH), evaluated_on(SOTA)) if d]
    if dates:
        oldest = min(dates)
        commits = commits_since(oldest)
        stale = len(commits) >= args.stale_after
        report["staleness"] = {
            "evaluated": f"{oldest:%Y-%m-%d}", "impl_commits_since": len(commits),
            "threshold": args.stale_after, "stale": stale,
            "commits": commits[:10],
        }
        soft_fail |= stale
    else:
        report["staleness"] = {"stale": True, "reason": "no Evaluated date parsed"}
        soft_fail = True

    if args.measure:
        measured = measure_facts()
        stated = stated_facts(HEALTH)
        drift = {}
        for k in measured:
            m, s = measured[k], stated.get(k)
            if m is None or s is None:
                continue
            same = abs(m - s) < (0.05 if k == "coverage_pct" else 0.5)
            drift[k] = {"stated": s, "measured": m, "ok": same}
            soft_fail |= not same
        report["facts"] = drift

    if args.json:
        print(json.dumps(report, indent=2))
    else:
        for name, a in report["arithmetic"].items():
            mark = "OK  " if a.get("ok") else "FAIL"
            detail = (f"computed {a['computed']} stated {a['stated']} header {a['header']}"
                      if a.get("ok") else a.get("reason"))
            print(f"[{mark}] arithmetic/{name}: {detail}")
        s = report["staleness"]
        mark = "WARN" if s.get("stale") else "OK  "
        print(f"[{mark}] staleness: evaluated {s.get('evaluated', '?')}, "
              f"{s.get('impl_commits_since', '?')} implementation commit(s) since "
              f"(threshold {s.get('threshold', args.stale_after)})")
        for c in s.get("commits", []):
            print(f"        {c}")
        if report["facts"] is not None:
            for k, d in report["facts"].items():
                mark = "OK  " if d["ok"] else "WARN"
                print(f"[{mark}] fact/{k}: stated {d['stated']}, measured {d['measured']}")
        if hard_fail:
            print("\nA scorecard's arithmetic does not add up. Fix the table or the "
                  "total before anything else; a wrong sum discredits every judgment "
                  "on the page.")
        elif soft_fail:
            print("\nScorecards are sound but stale or quoting old facts — run "
                  "/scorecard-refresh to re-form the judgments against the current code.")

    return 1 if hard_fail else (2 if soft_fail else 0)


if __name__ == "__main__":
    sys.exit(main())
